### ISSUE TITLE
Crashes when selecting Midi Output/Input dropdown boxes (OSX)

### ISSUE THREAD

**Issue by anonymouse197** [projectgus/hairless-midiserial#15]
Pretty self explanatory really; the application crashes when I try to click either the Midi Output or Input dropdown boxes.

I will do a fresh install and some fiddling and see what I can get.

**Comment by aterial** [comment]
Hey people,
I just want to tell my solution to the problem for anybody in the future who is as unexperienced as me.
All I needed to do is turn my MIDI IAC driver in the Audio MIDI Setup on. You will find out with google.

Greets

**Comment by liamcaff** [comment]
Thanks aterial! I just hit the same problem today. 

For anyone with the same issue, after I turned  the MIDI IAC Driver on, when in Hairless I had to choose the MIDI Out BEFORE the MIDI In. It was still crashing on me when I selected the MIDI in first.
