### ISSUE TITLE
64 bit Linux

### ISSUE THREAD

**Issue by XYR010** [projectgus/hairless-midiserial#27]
when compiling from source on 64 bit ubuntu this happens

hairless-midiserial-master/src/PortLatency_linux.cpp:54:17: error: ‘close’ was not declared in this scope
         close(fd);
                 ^
hairless-midiserial-master/src/PortLatency_linux.cpp:60:17: error: ‘close’ was not declared in this scope
         close(fd);
                 ^
hairless-midiserial-master/src/PortLatency_linux.cpp:71:17: error: ‘close’ was not declared in this scope
         close(fd);
                 ^
hairless-midiserial-master/src/PortLatency_linux.cpp:74:13: error: ‘close’ was not declared in this scope
     close(fd);
             ^

any idea how to fix this?

**Comment by projectgus** [comment]
Hi,

Weird, thanks for reporting this. close() is defined in unistd.h, at least on my system and I would expect all Linux systems! There's already an `include <unistd.h>` in that source file, though!

You can try running `man 2 close` and check that the man page gives the same header file. Is there any other compiler output, or are those errors the only part?

Angus

**Comment by XYR010** [comment]
i added <unistd.h> manually and everything worked fine ;) thx

**Comment by projectgus** [comment]
Oops, I'm sorry. I had the unistd.h include in a commit from way back last September, that I never pushed to github. Pushed now.
