### ISSUE TITLE
Build error on arduino software

### ISSUE THREAD

**Issue by Brandonn-Etheve** [projectgus/hairless-midiserial#28]
i've try to use the library with the arduino software (version 1.6.5) but i've got this error:
Arduino : 1.6.5 (Windows 7), Carte : "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Utilisation de la bibliothèque ardumidi prise dans le dossier : C:\Users\brd\Documents\Arduino\libraries\ardumidi (legacy)

C:\Users\brd\Downloads\arduino-1.6.5-r2-windows\arduino-1.6.5-r2\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -IC:\Users\brd\Downloads\arduino-1.6.5-r2-windows\arduino-1.6.5-r2\hardware\arduino\avr\cores\arduino -IC:\Users\brd\Downloads\arduino-1.6.5-r2-windows\arduino-1.6.5-r2\hardware\arduino\avr\variants\mega -IC:\Users\brd\Documents\Arduino\libraries\ardumidi C:\Users\brd\AppData\Local\Temp\build6592566260325845902.tmp\ardumidi_test_all_instruments.cpp -o C:\Users\brd\AppData\Local\Temp\build6592566260325845902.tmp\ardumidi_test_all_instruments.cpp.o 

C:\Users\brd\Downloads\arduino-1.6.5-r2-windows\arduino-1.6.5-r2\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -IC:\Users\brd\Downloads\arduino-1.6.5-r2-windows\arduino-1.6.5-r2\hardware\arduino\avr\cores\arduino -IC:\Users\brd\Downloads\arduino-1.6.5-r2-windows\arduino-1.6.5-r2\hardware\arduino\avr\variants\mega -IC:\Users\brd\Documents\Arduino\libraries\ardumidi -IC:\Users\brd\Documents\Arduino\libraries\ardumidi\utility C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp -o C:\Users\brd\AppData\Local\Temp\build6592566260325845902.tmp\ardumidi\ardumidi.cpp.o 

C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp: In function 'void midi_command(byte, byte, byte, byte)':
C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp:59:43: error: 'BYTE' was not declared in this scope
  Serial.print(command | (channel & 0x0F), BYTE);
                                           ^
C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp: In function 'void midi_command_short(byte, byte, byte)':
C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp:66:43: error: 'BYTE' was not declared in this scope
  Serial.print(command | (channel & 0x0F), BYTE);
                                           ^
C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp: In function 'void midi_print(char*, int)':
C:\Users\brd\Documents\Arduino\libraries\ardumidi\ardumidi.cpp:72:21: error: 'BYTE' was not declared in this scope
  Serial.print(0xFF, BYTE);
                     ^
Erreur lors de la compilation.

**Comment by projectgus** [comment]
Hi Brandonn,

Ardumidi library is unfortunately no longer supported - the original authors declared it finished a few years. I should stop distributing it with Hairless I guess.

The Arduino MIDI Library is up to date and works with Hairless (you just need to set the serial port baud rate to something that your computer can speak):
http://playground.arduino.cc/Main/MIDILibrary

Happy MIDI-ing!

Angus
