### ISSUE TITLE
Only 1 step with a controller in Logic

### ISSUE THREAD

**Issue by therealarckler** [projectgus/hairless-midiserial#29]
I made a controller with a distance sensor, it works perfectly with Ableton and several others softwares. But with logic it should be recognized as "controller Ch 1, 106, Lo7". But Logic says "controller Ch 1, 0, Lo7". It means that their is no a hundred steps but just one, so it acts like an on/off button.
It tried with Logic X and previous versions and I have the same result...

**Comment by projectgus** [comment]
Hi therealarckler,

Glad you're finding hairless-midiserial useful!

Midi is pretty basic regarding ranges of steps, etc. It doesn't provide any metadata at all, usually the software the controller talks to just detects the range of motion that it sees and assumes that's everything (there's sometimes a calibration phase where you try to send all the range from every input, so the software can see what's available).

I'm not familiar with Logic so I can't tell you how to get logic to do this calibration/setup pass, but I'm guessing doing that (and sending the full range of 'distance' outputs from your sensor) will fix this problem.

Cheers,


Angus

**Comment by therealarckler** [comment]
Hi Angus!

I have a special question for you, I am making a midi controller that works
with a distance sensor. I would like everybody to use it! So I made a
website in order to sell it at a low price (25€), I produce myself all the
instruments. And of course it is an open source project, every secret is
given. I made manuals and videos so that everybody can do it with a cutter
and some glue for 4€.
So I would like to know if I have the right to use hairless. Of course I
wouldn't sell it but I need it in order to run the device. It would be
given for free.

Thanks!

Oscar.

2016-01-04 2:27 GMT+01:00 Angus Gratton <notifications@github.com>:

**Comment by projectgus** [comment]
Hi Oscar,

You absolutely have the right. :) If you're giving it away, all you need to do is distribute the licensing information (it's in the About box so if you don't change the software program then that's enough to comply.) A direct link back from your site to the hairless site would be appreciated, but it's not even required.

Make sure to let me know when the website is up and I'll check it out. :)

Cheers,


Angus

**Comment by therealarckler** [comment]
Hello Angus!

I am still developing my project. And I will finish it in two months. With
crazy music videos, kickstarter and all the stuff.
So I have an another question for you. I noticed that an official Arduino
nano is not working with a PC on Hairless. It is written " It doesn't seems
to be a FTDI device. No latency trick...". I talked about it with a guy who
knows well electronics. He told me that the problem could be because of the
chip in arduino that no longer use FTDI. If he is right, could you upgrade
the software for the new arduinos?

Thanks, I'll send an instrument for you as soon as I finished the project!
here is a picture of one of the prototypes.

2016-01-20 23:04 GMT+01:00 Angus Gratton <notifications@github.com>:

**Comment by projectgus** [comment]
Hi Oscar,

The Nano should still work, even with this message printed out. The message just means that because it's not an FTDI, we don't need to do any tricks to get the latency down. Do you think it might be something else?

The picture didn't come through, but the project sounds exciting. Look forward to seeing it.


Angus

**Comment by projectgus** [comment]
I'm going to close this issue for now,  as I think it's taken care of. Good luck launching your project.

**Comment by therealarckler** [comment]
Hi angus!

I resolved the problem of steps in Logic pro! It would be cool to notice it
in your github, I don't where to tell it, I'm not a programer at all. Well,
in logic pro you need to go to preferences > advanced options > check the
MIDI option. It will activate the expert view for the midi mapping. Then,
when you map a knob, you have to select "unsigned" format and "mesured"
mode.

I almost finished the instrument! We are now making a great commercial
video. So I have a question, it is about global design. I would like to
know if I can modify the hairless interface and put my logo on the icon. It
would much more professional if I can do it. Obviously it would be written
Powered by Hairless in big letters with a link to your website.

Thanks again!

Oscar

2016-01-04 2:27 GMT+01:00 Angus Gratton <notifications@github.com>:
