### ISSUE TITLE
trying to start hairless on linux mint cinnamon 17.2. stopps with error message

### ISSUE THREAD

**Issue by rappgit** [projectgus/hairless-midiserial#32]
[ SOLVED ] "ALSA lib conf.c:3314:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

RtMidiIn::initialize: error creating ALSA sequencer input client object.

terminate called after throwing an instance of 'RtError'
  what():  RtMidiIn::initialize: error creating ALSA sequencer input client object.
Abgebrochen"

Some days ago, everything went well with hairless. Finally changed some configuration with and round jackd and alsa, but what in special went wrong? anybody with an idea?

regards
christoph

**Comment by rappgit** [comment]
apt-get install libasound2-plugins:i386 solved the hook.
everything fine again with hairless-midiserial :-)
regards
christoph

**Comment by projectgus** [comment]
Hi Christoph,

Glad you got it sorted out. Sorry I didn't reply earlier.

Angus
