### ISSUE TITLE
Hairless, MakeyMakey, Windows 10: no notes in MIDI log

### ISSUE THREAD

**Issue by X-Raym** [projectgus/hairless-midiserial#36]
Hi,

Hairless doesn't seem to receive any MIDI signal from my moded Makey Makey.

I don't think this is related to [how I programmed](http://www.instructables.com/id/Makey-Makey-MIDI-controller/) the Makey Makey (so that it can send MIDI notes) because it works flawlessly with Hairless on MacOS, but on Windows, I have this message:
**FTDI drivers don't seem to be installed. Not attempting any FTDI latency tricks.**

![Screenshot](https://api.monosnap.com/rpc/file/download?id=vzd9A898FPgsGaqrdOzzXxs2j5cVfw)
![Settings](https://monosnap.com/file/x9GtIqVJSRtcpWHEoAbZj829DYYZD7.png)

(Note: baud speed is 38400 just as adviced in the Makey Makey tutorial).

I [tried to install the FTDI driver](https://learn.sparkfun.com/tutorials/how-to-install-ftdi-drivers/windows---in-depths) to see if it solve the problems but it did not. They still appear missing in Hairless.
Could the fact that Hairless doesn't see any MIDI note from my Makey Makey be related to this problem ? or is it something with the Makey Makey code I took ?

Did I missed something?

Thanks for your support!

**Comment by DJShades** [comment]
Is the incoming signal indicator, next to the serial device drop-down box, flashing when you attempt to send a MIDI message? If not I'd say it was a problem with the serial side of things before Hairless as I get the same FTDI message and everything still works.

Have you tried to temporarily using serial monitoring software to see if you're actually receiving any data via serial?

**Comment by X-Raym** [comment]
No flash at all, only flash on the Makey Makey controller.

I don't really know how to make serial monitoring  do you have any good freeware or tutorial to advice me?

I tried [Free Serial Protocol Analyser](http://freeserialanalyzer.com/), but not any graph displayed something. But maybe it is just because I don't know how to properly use it.

Thanks again for your quick support!

**Comment by X-Raym** [comment]
Ok I just try Serial Monitoring with [Serial Port Monitor](http://www.eltima.com/fr/products/serial-port-monitor/), and I get a result.

![ScreenCapture](http://i.imgur.com/0Te6GmV.gif)
[ScreenCapture](http://i.imgur.com/0Te6GmV.gifv)

Does that help, doc? :)

**Comment by DJShades** [comment]
Hey, sorry for taking a bit longer to respond this time.

I've just noticed that the COM ports in the screenshots may be different. In the shot of Hairless you're directing it to "Périphérique Série USB (COM9)" but it appears that you're directing the serial port monitor to "COM5" (I can't quite tell because the text is grey on a blue background, but it certainly looks like a 5 on the end).

This may sound silly but can you confirm that you are pointing Hairless at the correct COM port?

**Comment by X-Raym** [comment]
Don't worry, you can take your time to answer :)

COM port is not the same in the different screenshots because I plug the makey makey on different USB port between these screenshots, for testing.

While I was trying to debug this, I noticed that I can get MIDI message after if I open and close monitoring on Serial Port Monitor. I don't why, but this seems to "unlocked" the port. Just activating / deactivating the port on Hairless is not enough.

Here is a [screen capture](http://i.imgur.com/BDbSqsP.mp4).

Any idea about this weird behavior ?

**Comment by projectgus** [comment]
Hi @X-Raym,

Thanks for sending all the details, captures, etc. I haven't seen anything like this before.

If you set Flow Control to "Hardware Flow Control" in Serial Port settings then does anything happen differently?

Angus

**Comment by X-Raym** [comment]
@projectgus
Oh man, this seems to work ! So cool ! :tada: 
I can't believe the solution was so simple, in front of my noze from the beginning.

I think I know how I missed that: it seems that sometimes (I don't really find the pattern) the bridge have to be switch on/off before it works.

In the following screen capture, I pressed Makey Makey controls every time I changed a parameter. As you can see, some times nothing is send, unless it is reset, by activating deactivating the bridge, or by reselecting the COM.
![ScreenCapture](http://i.imgur.com/OobFvwo.gif)

Maybe it worth updating the The Hairless FAQ told which currently tells 

> Try disabling Flow Control if it was enabled.

with

> Try different Flow control, and deativate/reactivate the bridge after the parameter change.

Thanks both of you for your support, and for your nice software :)

Note: I just made a [video](http://www.extremraym.com/en/makey-makey-midi-jsfx/) which shows hairless-midi in action. It is not a video strictly _about_ it, but it wouldn't have been possible without it, and so hairless-midi GUI is displayed at the beginning. Maybe you could enjoy it :wink:  Cheers !

**Comment by projectgus** [comment]
Cool project! I appreciate the link. And thanks for suggesting the update to the FAQ, I added a note to suggest enabling it.

**Comment by X-Raym** [comment]
Thanks for all ! :)
