### ISSUE TITLE
error while loading shared libraries: libasound.so.2

### ISSUE THREAD

**Issue by eduszesz** [projectgus/hairless-midiserial#38]
Hello,

I downloaded the hairless-midiserial-0.4-linux.tgz file from the project main page, extracted it, but when I try to run the application the following error message shows up:
"error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory".
libasound2 library is already installed.
How can I fix this issue?
Thanks in advance

**Comment by projectgus** [comment]
Hi @eduszesz,

Thanks for reporting this issue. What Linux distribution (& distribution version) are you using?

Angus

**Comment by eduszesz** [comment]
Hi,

I'm using ubuntu 16.04 64bits.

Regards

Eduardo Szesz

2016-10-16 7:53 GMT-02:00 Angus Gratton <notifications@github.com>:

**Comment by projectgus** [comment]
The Linux build is 32-bit, so you'll need 32-bit libasound to match. I think on Ubuntu the command is "apt-get install libasound:i386".

Angus


-------- Original Message --------

**Comment by eduszesz** [comment]
Hi,

I installed the 32-bits liasound and it solve the problem.

Thank you for the help

Best regards

Eduardo

2016-10-17 9:28 GMT-02:00 Angus Gratton <notifications@github.com>:

**Comment by projectgus** [comment]
No problems, glad you got it sorted out.
