### ISSUE TITLE
Failed to get serial port info for /dev/ttyUSB1, cannot set low latency mode

### ISSUE THREAD

**Issue by lokk3d** [projectgus/hairless-midiserial#40]
Hi, if i try to connect my arduino nano, i get this error, how can i solve?

**Comment by projectgus** [comment]
This message should only be a warning that we couldn't tweak the latency on the USB adapter (it's not necessary for some adapter types.) Is it also not working?

**Comment by lanciafool** [comment]
Hi, i am using Hairless to send midi signals for drum trigger. I used it on Mac with no problems but now trying on Linux Ubuntu and it comes up with the error saying "cannot set low latency mode".  it still works in sending the midi notes but i really want the lowest latency possible. Not sure what to do. I am using one of the chinese arduino clones.

**Comment by projectgus** [comment]
@lanciafool Do you know what USB/serial chip the Arduino clone is using? Probably there is no support for changing the latency on this chip. Don't worry about it too much unless the latency is bothering you, the defaults are usually quite good.

**Comment by lanciafool** [comment]
hi, i believe the chip is the CH341SER.  when i had it working on the mac i had to download a driver for that chipset.  The latency does seem to be prevelant on the Ubuntu so if there was a way to reduce it that would be great!

**Comment by projectgus** [comment]
I don't think the CH341 has any support for setting serial latency, unfortunately. If you get something with an FTDI chipset then the driver has support to reduce it.
