### ISSUE TITLE
Won't execute double-clicking at "hairless-midiserial" - Ubuntu 16.04

### ISSUE THREAD

**Issue by ciclosonoro** [projectgus/hairless-midiserial#41]
I use Ubuntu and it was working fine until I upgrade from 14.04 to 16.04. Now I double click "hairless-midiserial" and nothing happens =(

**Comment by danielneumaier2222** [comment]
Same for me ... i have no idea how i can start this script ...

**Comment by ciclosonoro** [comment]
Right click and try to check the "allow executing file as program" option

**Comment by sleeplessCortes** [comment]
I have the same problem,  it is not possible starting, neither with "./hairless-midiserial" (can not find ) nor with double- or rightclick to execute file as a programm.......

**Comment by ciclosonoro** [comment]
Since it displayed "can not find", make sure you're in the right folder at the terminal and use
sudo ./hairless-midiserial

**Comment by projectgus** [comment]
If you have 64-bit Linux now, you'll needto install the compatibility libraries shown here:
https://github.com/projectgus/hairless-midiserial/issues/47#issuecomment-449911830

I don't know why it'd need you to run it as `sudo`, maybe so it has permissions for the serial port? There's a better way to do this: https://askubuntu.com/a/112572

**Comment by dmukasey** [comment]
Install the dependencies

The Hairless program is a 32-bit executable, so on most modern 64-bit Linux distributions, you'll have to explicitly install some 32-bit libraries to be able to run it:

sudo apt install libasound2:i386 libsm6:i386 libxrender1:i386 libfontconfig1:i386 libasound2-plugins:i386

original article: https://tttapa.github.io/Pages/Ubuntu/Software-Installation/Arduino/Hairless-MIDI.html
