### ISSUE TITLE
Exectuable file not running on Linux

### ISSUE THREAD

**Issue by geofolded** [projectgus/hairless-midiserial#50]
I have installed the .tzg file for Linux and extracted the files, but when I try to run the program from the command line, I get the following error message.

ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

RtMidiIn::initialize: error creating ALSA sequencer input client object.

terminate called after throwing an instance of 'RtError'
  what():  RtMidiIn::initialize: error creating ALSA sequencer input client object.
Aborted

I have looked at another thread of someone who had this exact same issue, and they ran the following code to get it to work.

apt-get install libasound2:i386 libasound2-plugins:i386

When I ran this though it asked for more dependencies which I added until I finally came to one that it said it couldn't find.

apt-get install libasound2:i386 libasound2-plugins:i386 libpulse0:i386 libjson-c2:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libjson-c2:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libjson-c2:i386' has no installation candidate

Any thoughts or ideas? I'm running AVLinux, and am somewhat new to Linux and coding in general.

**Comment by jayknowstheway** [comment]
Hairless is still not working on linux, the message I get when I try to run it via terminal is that there is no file or directory. Double clicking the file does nothing.

**Comment by projectgus** [comment]
@geofolded I don't know AVLinux, but if it's APT-based then running `apt-get update` and then re-running the other command should work. I just tried on 64-bit Ubuntu 16.04 (Xenial) and was able to make it run.

@jayknowstheway The Hairless release (from 2012) was built for 32-bit Linux, you get the "No such file or directory" error if using 64-bit Linux without any compatibility libraries for 32-bit Linux installed. The exact steps to install 32-bit compatibility depend on your Linux distribution, check their docs.
